// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: OakShared.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace OakSave
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Vec3 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x")]
        public float X { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"y")]
        public float Y { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"z")]
        public float Z { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameStatSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stat_value")]
        public int StatValue { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"stat_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string StatPath { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class InventoryCategorySaveData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"base_category_definition_hash")]
        public uint BaseCategoryDefinitionHash { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"quantity")]
        public int Quantity { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OakSDUSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sdu_level")]
        public int SduLevel { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"sdu_data_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SduDataPath { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RegisteredDownloadableEntitlement : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"consumed")]
        public uint Consumed { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"registered")]
        public bool Registered { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"seen")]
        public bool Seen { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RegisteredDownloadableEntitlements : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entitlement_source_asset_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string EntitlementSourceAssetPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"entitlement_ids", IsPacked = true)]
        public long[] EntitlementIds { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"entitlements")]
        public global::System.Collections.Generic.List<RegisteredDownloadableEntitlement> Entitlements { get; } = new global::System.Collections.Generic.List<RegisteredDownloadableEntitlement>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChallengeStatSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"current_stat_value")]
        public int CurrentStatValue { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"challenge_stat_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ChallengeStatPath { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OakChallengeRewardSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"challenge_reward_claimed")]
        public bool ChallengeRewardClaimed { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChallengeSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"completed_count")]
        public int CompletedCount { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"is_active")]
        public bool IsActive { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"currently_completed")]
        public bool CurrentlyCompleted { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"completed_progress_level")]
        public int CompletedProgressLevel { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"progress_counter")]
        public int ProgressCounter { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"stat_instance_state")]
        public global::System.Collections.Generic.List<ChallengeStatSaveGameData> StatInstanceStates { get; } = new global::System.Collections.Generic.List<ChallengeStatSaveGameData>();

        [global::ProtoBuf.ProtoMember(7, Name = @"challenge_class_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ChallengeClassPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"challenge_reward_info")]
        public global::System.Collections.Generic.List<OakChallengeRewardSaveGameData> ChallengeRewardInfoes { get; } = new global::System.Collections.Generic.List<OakChallengeRewardSaveGameData>();

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
