// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: OakSave.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace OakSave
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerClassSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"player_class_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlayerClassPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"dlc_package_id")]
        public uint DlcPackageId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResourcePoolSavegameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"amount")]
        public float Amount { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"resource_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ResourcePath { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RegionSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"game_stage")]
        public int GameStage { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"play_through_idx")]
        public int PlayThroughIdx { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"region_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RegionPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"dlc_package_id")]
        public uint DlcPackageId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class InventoryBalanceStateInitializationData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"game_stage")]
        public int GameStage { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"inventory_data")]
        [global::System.ComponentModel.DefaultValue("")]
        public string InventoryData { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"inventory_balance_data")]
        [global::System.ComponentModel.DefaultValue("")]
        public string InventoryBalanceData { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"manufacturer_data")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ManufacturerData { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"part_list")]
        public global::System.Collections.Generic.List<string> PartLists { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(6, Name = @"generic_part_list")]
        public global::System.Collections.Generic.List<string> GenericPartLists { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(7, Name = @"additional_data")]
        public byte[] AdditionalData { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"customization_part_list")]
        public global::System.Collections.Generic.List<string> CustomizationPartLists { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OakInventoryItemSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"item_serial_number")]
        public byte[] ItemSerialNumber { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"pickup_order_index")]
        public int PickupOrderIndex { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"flags")]
        public int Flags { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"weapon_skin_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string WeaponSkinPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"development_save_data")]
        public InventoryBalanceStateInitializationData DevelopmentSaveData { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EquippedInventorySaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"inventory_list_index")]
        public int InventoryListIndex { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"enabled")]
        public bool Enabled { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"slot_data_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SlotDataPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"trinket_data_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TrinketDataPath { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OakAbilityTreeItemSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"item_asset_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ItemAssetPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"points")]
        public int Points { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"max_points")]
        public int MaxPoints { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"tree_identifier")]
        public int TreeIdentifier { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OakAbilitySlotSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ability_class_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AbilityClassPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"slot_asset_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SlotAssetPath { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OakActionAbilityAugmentSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"action_ability_class_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ActionAbilityClassPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"slot_asset_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SlotAssetPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"augment_asset_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AugmentAssetPath { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OakActionAbilityAugmentConfigurationSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ability_class_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AbilityClassPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"augment_asset_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AugmentAssetPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"mod_slot_asset_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ModSlotAssetPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"mod_asset_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ModAssetPath { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OakPlayerAbilitySaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ability_points")]
        public int AbilityPoints { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"tree_item_list")]
        public global::System.Collections.Generic.List<OakAbilityTreeItemSaveGameData> TreeItemLists { get; } = new global::System.Collections.Generic.List<OakAbilityTreeItemSaveGameData>();

        [global::ProtoBuf.ProtoMember(3, Name = @"ability_slot_list")]
        public global::System.Collections.Generic.List<OakAbilitySlotSaveGameData> AbilitySlotLists { get; } = new global::System.Collections.Generic.List<OakAbilitySlotSaveGameData>();

        [global::ProtoBuf.ProtoMember(4, Name = @"augment_slot_list")]
        public global::System.Collections.Generic.List<OakActionAbilityAugmentSaveGameData> AugmentSlotLists { get; } = new global::System.Collections.Generic.List<OakActionAbilityAugmentSaveGameData>();

        [global::ProtoBuf.ProtoMember(5, Name = @"augment_configuration_list")]
        public global::System.Collections.Generic.List<OakActionAbilityAugmentConfigurationSaveGameData> AugmentConfigurationLists { get; } = new global::System.Collections.Generic.List<OakActionAbilityAugmentConfigurationSaveGameData>();

        [global::ProtoBuf.ProtoMember(6, Name = @"tree_grade")]
        public int TreeGrade { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MissionStatusPlayerSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"status")]
        public MissionState Status { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"has_been_viewed_in_log")]
        public bool HasBeenViewedInLog { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"objectives_progress", IsPacked = true)]
        public int[] ObjectivesProgresses { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"mission_class_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string MissionClassPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"active_objective_set_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ActiveObjectiveSetPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"dlc_package_id")]
        public uint DlcPackageId { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"kickoff_played")]
        public bool KickoffPlayed { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"league_instance")]
        public uint LeagueInstance { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum MissionState
        {
            [global::ProtoBuf.ProtoEnum(Name = @"MS_NotStarted")]
            MSNotStarted = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"MS_Active")]
            MSActive = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"MS_Complete")]
            MSComplete = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"MS_Failed")]
            MSFailed = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"MS_Unknown")]
            MSUnknown = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MissionPlaythroughSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"mission_list")]
        public global::System.Collections.Generic.List<MissionStatusPlayerSaveGameData> MissionLists { get; } = new global::System.Collections.Generic.List<MissionStatusPlayerSaveGameData>();

        [global::ProtoBuf.ProtoMember(2, Name = @"tracked_mission_class_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TrackedMissionClassPath { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ActiveFastTravelSaveData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"active_travel_station_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ActiveTravelStationName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"blacklisted")]
        public bool Blacklisted { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlaythroughActiveFastTravelSaveData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"active_travel_stations")]
        public global::System.Collections.Generic.List<ActiveFastTravelSaveData> ActiveTravelStations { get; } = new global::System.Collections.Generic.List<ActiveFastTravelSaveData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DiscoveredAreaInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"discovered_area_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DiscoveredAreaName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"discovered_playthroughs")]
        public uint DiscoveredPlaythroughs { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DiscoveredLevelInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"discovered_level_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DiscoveredLevelName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"discovered_playthroughs")]
        public uint DiscoveredPlaythroughs { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"discovered_area_info")]
        public global::System.Collections.Generic.List<DiscoveredAreaInfo> DiscoveredAreaInfoes { get; } = new global::System.Collections.Generic.List<DiscoveredAreaInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DiscoveredPlanetInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"discovered_planet")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DiscoveredPlanet { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"is_new_planet")]
        public bool IsNewPlanet { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DiscoverySaveData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"discovered_level_info")]
        public global::System.Collections.Generic.List<DiscoveredLevelInfo> DiscoveredLevelInfoes { get; } = new global::System.Collections.Generic.List<DiscoveredLevelInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VehicleUnlockedSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"asset_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AssetPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"just_unlocked")]
        public bool JustUnlocked { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OakCARMenuVehicleConfigSaveData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"loadout_save_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LoadoutSaveName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"body_asset_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string BodyAssetPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"wheel_asset_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string WheelAssetPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"armor_asset_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ArmorAssetPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"core_mod_asset_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CoreModAssetPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"gunner_weapon_asset_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string GunnerWeaponAssetPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"driver_weapon_asset_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DriverWeaponAssetPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"ornament_asset_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string OrnamentAssetPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(9, Name = @"material_decal_asset_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string MaterialDecalAssetPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10, Name = @"material_asset_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string MaterialAssetPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11, Name = @"color_index_1")]
        public int ColorIndex1 { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"color_index_2")]
        public int ColorIndex2 { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"color_index_3")]
        public int ColorIndex3 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CustomPlayerColorSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"color_parameter")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ColorParameter { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"applied_color")]
        public Vec3 AppliedColor { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"split_color")]
        public Vec3 SplitColor { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"use_default_color")]
        public bool UseDefaultColor { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"use_default_split_color")]
        public bool UseDefaultSplitColor { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuardianRankSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"guardian_rank")]
        public int GuardianRank { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"guardian_experience")]
        public int GuardianExperience { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuardianRankRewardCharacterSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"num_tokens")]
        public int NumTokens { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"is_enabled")]
        public bool IsEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"reward_data_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RewardDataPath { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuardianRankPerkCharacterSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"is_enabled")]
        public bool IsEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"perk_data_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PerkDataPath { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuardianRankCharacterSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"guardian_available_tokens")]
        public int GuardianAvailableTokens { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"guardian_rank")]
        public int GuardianRank { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"guardian_experience")]
        public int GuardianExperience { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"rank_rewards")]
        public global::System.Collections.Generic.List<GuardianRankRewardCharacterSaveGameData> RankRewards { get; } = new global::System.Collections.Generic.List<GuardianRankRewardCharacterSaveGameData>();

        [global::ProtoBuf.ProtoMember(5, Name = @"rank_perks")]
        public global::System.Collections.Generic.List<GuardianRankPerkCharacterSaveGameData> RankPerks { get; } = new global::System.Collections.Generic.List<GuardianRankPerkCharacterSaveGameData>();

        [global::ProtoBuf.ProtoMember(6, Name = @"guardian_reward_random_seed")]
        public int GuardianRewardRandomSeed { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"new_guardian_experience")]
        public long NewGuardianExperience { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"is_rank_system_enabled")]
        public bool IsRankSystemEnabled { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrewQuartersDecorationSaveData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"decoration_index")]
        public int DecorationIndex { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"decoration_data_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DecorationDataPath { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrewQuartersSaveData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"preferred_room_assignment")]
        public int PreferredRoomAssignment { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"decorations")]
        public global::System.Collections.Generic.List<CrewQuartersDecorationSaveData> Decorations { get; } = new global::System.Collections.Generic.List<CrewQuartersDecorationSaveData>();

        [global::ProtoBuf.ProtoMember(3, Name = @"room_data_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RoomDataPath { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrewQuartersGunRackItemSaveData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"encrypted_serial_number")]
        public byte[] EncryptedSerialNumber { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"slot_asset_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SlotAssetPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"development_save_data")]
        public InventoryBalanceStateInitializationData DevelopmentSaveData { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrewQuartersGunRackSaveData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"rack_save_data")]
        public global::System.Collections.Generic.List<CrewQuartersGunRackItemSaveData> RackSaveDatas { get; } = new global::System.Collections.Generic.List<CrewQuartersGunRackItemSaveData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EchoLogSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"has_been_seen_in_log")]
        public bool HasBeenSeenInLog { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"echo_log_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string EchoLogPath { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MapIDData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"zone_name_id")]
        public uint ZoneNameId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"map_name_id")]
        public uint MapNameId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameStateSaveData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"last_traveled_map_id")]
        public MapIDData LastTraveledMapId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"mayhem_level")]
        public int MayhemLevel { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChallengeCategoryProgressSaveData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"category_progress")]
        public byte[] CategoryProgress { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OakPlayerCharacterAugmentSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"slot_asset_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SlotAssetPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"augment_asset_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AugmentAssetPath { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OakPlayerCharacterSlotSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"augment_slot_list")]
        public global::System.Collections.Generic.List<OakPlayerCharacterAugmentSaveGameData> AugmentSlotLists { get; } = new global::System.Collections.Generic.List<OakPlayerCharacterAugmentSaveGameData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UITrackingSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"has_seen_skill_menu_unlock")]
        public bool HasSeenSkillMenuUnlock { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"has_seen_guardian_rank_menu_unlock")]
        public bool HasSeenGuardianRankMenuUnlock { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"has_seen_echo_boot_ammo_bar")]
        public bool HasSeenEchoBootAmmoBar { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"has_seen_echo_boot_shield_bar")]
        public bool HasSeenEchoBootShieldBar { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"has_seen_echo_boot_grenades")]
        public bool HasSeenEchoBootGrenades { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"highest_thvm_breadcrumb_seen")]
        public int HighestThvmBreadcrumbSeen { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"inventory_slot_unlocks_seen")]
        public global::System.Collections.Generic.List<string> InventorySlotUnlocksSeens { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(8, Name = @"saved_spin_offset")]
        public int SavedSpinOffset { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlanetCycleInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"planet_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlanetName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"cycle_length")]
        public float CycleLength { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"last_cached_time")]
        public float LastCachedTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TimeOfDaySaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"planet_cycle_info")]
        public global::System.Collections.Generic.List<PlanetCycleInfo> PlanetCycleInfoes { get; } = new global::System.Collections.Generic.List<PlanetCycleInfo>();

        [global::ProtoBuf.ProtoMember(2, Name = @"planet_cycle")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlanetCycle { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"LevelPersistence_Actor_SaveGameData")]
    public partial class LevelPersistenceActorSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"actor_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ActorName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"timer_remaining")]
        public int TimerRemaining { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"LevelPersistence_Level_SaveGameData")]
    public partial class LevelPersistenceLevelSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"level_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LevelName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"saved_actors")]
        public global::System.Collections.Generic.List<LevelPersistenceActorSaveGameData> SavedActors { get; } = new global::System.Collections.Generic.List<LevelPersistenceActorSaveGameData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GbxZoneMapFODSavedLevelData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"level_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LevelName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"fod_texture_size")]
        public uint FodTextureSize { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"num_chunks")]
        public uint NumChunks { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"discovery_percentage")]
        public float DiscoveryPercentage { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"data_state")]
        public uint DataState { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"data_revision")]
        public uint DataRevision { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"fod_data")]
        public byte[] FodData { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GbxZoneMapFODSaveGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"level_data")]
        public global::System.Collections.Generic.List<GbxZoneMapFODSavedLevelData> LevelDatas { get; } = new global::System.Collections.Generic.List<GbxZoneMapFODSavedLevelData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Character : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"save_game_id")]
        public uint SaveGameId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"last_save_timestamp")]
        public long LastSaveTimestamp { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"time_played_seconds")]
        public uint TimePlayedSeconds { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"player_class_data")]
        public PlayerClassSaveGameData PlayerClassData { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"resource_pools")]
        public global::System.Collections.Generic.List<ResourcePoolSavegameData> ResourcePools { get; } = new global::System.Collections.Generic.List<ResourcePoolSavegameData>();

        [global::ProtoBuf.ProtoMember(6, Name = @"saved_regions")]
        public global::System.Collections.Generic.List<RegionSaveGameData> SavedRegions { get; } = new global::System.Collections.Generic.List<RegionSaveGameData>();

        [global::ProtoBuf.ProtoMember(7, Name = @"experience_points")]
        public int ExperiencePoints { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"game_stats_data")]
        public global::System.Collections.Generic.List<GameStatSaveGameData> GameStatsDatas { get; } = new global::System.Collections.Generic.List<GameStatSaveGameData>();

        [global::ProtoBuf.ProtoMember(9, Name = @"inventory_category_list")]
        public global::System.Collections.Generic.List<InventoryCategorySaveData> InventoryCategoryLists { get; } = new global::System.Collections.Generic.List<InventoryCategorySaveData>();

        [global::ProtoBuf.ProtoMember(10, Name = @"inventory_items")]
        public global::System.Collections.Generic.List<OakInventoryItemSaveGameData> InventoryItems { get; } = new global::System.Collections.Generic.List<OakInventoryItemSaveGameData>();

        [global::ProtoBuf.ProtoMember(11, Name = @"equipped_inventory_list")]
        public global::System.Collections.Generic.List<EquippedInventorySaveGameData> EquippedInventoryLists { get; } = new global::System.Collections.Generic.List<EquippedInventorySaveGameData>();

        [global::ProtoBuf.ProtoMember(12, Name = @"active_weapon_list", IsPacked = true)]
        public int[] ActiveWeaponLists { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"ability_data")]
        public OakPlayerAbilitySaveGameData AbilityData { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"last_play_through_index")]
        public int LastPlayThroughIndex { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"playthroughs_completed")]
        public int PlaythroughsCompleted { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"show_new_playthrough_notification")]
        public bool ShowNewPlaythroughNotification { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"mission_playthroughs_data")]
        public global::System.Collections.Generic.List<MissionPlaythroughSaveGameData> MissionPlaythroughsDatas { get; } = new global::System.Collections.Generic.List<MissionPlaythroughSaveGameData>();

        [global::ProtoBuf.ProtoMember(21, Name = @"active_travel_stations")]
        public global::System.Collections.Generic.List<string> ActiveTravelStations { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(22, Name = @"discovery_data")]
        public DiscoverySaveData DiscoveryData { get; set; }

        [global::ProtoBuf.ProtoMember(23, Name = @"last_active_travel_station")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LastActiveTravelStation { get; set; } = "";

        [global::ProtoBuf.ProtoMember(24, Name = @"vehicles_unlocked_data")]
        public global::System.Collections.Generic.List<VehicleUnlockedSaveGameData> VehiclesUnlockedDatas { get; } = new global::System.Collections.Generic.List<VehicleUnlockedSaveGameData>();

        [global::ProtoBuf.ProtoMember(25, Name = @"vehicle_parts_unlocked")]
        public global::System.Collections.Generic.List<string> VehiclePartsUnlockeds { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(26, Name = @"vehicle_loadouts")]
        public global::System.Collections.Generic.List<OakCARMenuVehicleConfigSaveData> VehicleLoadouts { get; } = new global::System.Collections.Generic.List<OakCARMenuVehicleConfigSaveData>();

        [global::ProtoBuf.ProtoMember(27, Name = @"vehicle_last_loadout_index")]
        public int VehicleLastLoadoutIndex { get; set; }

        [global::ProtoBuf.ProtoMember(28, Name = @"challenge_data")]
        public global::System.Collections.Generic.List<ChallengeSaveGameData> ChallengeDatas { get; } = new global::System.Collections.Generic.List<ChallengeSaveGameData>();

        [global::ProtoBuf.ProtoMember(29, Name = @"sdu_list")]
        public global::System.Collections.Generic.List<OakSDUSaveGameData> SduLists { get; } = new global::System.Collections.Generic.List<OakSDUSaveGameData>();

        [global::ProtoBuf.ProtoMember(30, Name = @"selected_customizations")]
        public global::System.Collections.Generic.List<string> SelectedCustomizations { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(31, Name = @"equipped_emote_customizations", IsPacked = true)]
        public int[] EquippedEmoteCustomizations { get; set; }

        [global::ProtoBuf.ProtoMember(32, Name = @"selected_color_customizations")]
        public global::System.Collections.Generic.List<CustomPlayerColorSaveGameData> SelectedColorCustomizations { get; } = new global::System.Collections.Generic.List<CustomPlayerColorSaveGameData>();

        [global::ProtoBuf.ProtoMember(33, Name = @"guardian_rank")]
        public GuardianRankSaveGameData GuardianRank { get; set; }

        [global::ProtoBuf.ProtoMember(34, Name = @"crew_quarters_room")]
        public CrewQuartersSaveData CrewQuartersRoom { get; set; }

        [global::ProtoBuf.ProtoMember(35, Name = @"crew_quarters_gun_rack")]
        public CrewQuartersGunRackSaveData CrewQuartersGunRack { get; set; }

        [global::ProtoBuf.ProtoMember(36, Name = @"unlocked_echo_logs")]
        public global::System.Collections.Generic.List<EchoLogSaveGameData> UnlockedEchoLogs { get; } = new global::System.Collections.Generic.List<EchoLogSaveGameData>();

        [global::ProtoBuf.ProtoMember(37, Name = @"has_played_special_echo_log_insert_already")]
        public bool HasPlayedSpecialEchoLogInsertAlready { get; set; }

        [global::ProtoBuf.ProtoMember(38, Name = @"nickname_mappings")]
        public global::System.Collections.Generic.List<NicknameMappingsEntry> NicknameMappings { get; } = new global::System.Collections.Generic.List<NicknameMappingsEntry>();

        [global::ProtoBuf.ProtoMember(39, Name = @"last_traveled_map_id")]
        public MapIDData LastTraveledMapId { get; set; }

        [global::ProtoBuf.ProtoMember(40, Name = @"challenge_category_completion_pcts")]
        public ChallengeCategoryProgressSaveData ChallengeCategoryCompletionPcts { get; set; }

        [global::ProtoBuf.ProtoMember(41, Name = @"character_slot_save_game_data")]
        public OakPlayerCharacterSlotSaveGameData CharacterSlotSaveGameData { get; set; }

        [global::ProtoBuf.ProtoMember(42, Name = @"ui_tracking_save_game_data")]
        public UITrackingSaveGameData UiTrackingSaveGameData { get; set; }

        [global::ProtoBuf.ProtoMember(43, Name = @"preferred_character_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PreferredCharacterName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(44, Name = @"name_character_limit")]
        public int NameCharacterLimit { get; set; }

        [global::ProtoBuf.ProtoMember(45, Name = @"preferred_group_mode")]
        public uint PreferredGroupMode { get; set; }

        [global::ProtoBuf.ProtoMember(46, Name = @"time_of_day_save_game_data")]
        public TimeOfDaySaveGameData TimeOfDaySaveGameData { get; set; }

        [global::ProtoBuf.ProtoMember(47, Name = @"level_persistence_data")]
        public global::System.Collections.Generic.List<LevelPersistenceLevelSaveGameData> LevelPersistenceDatas { get; } = new global::System.Collections.Generic.List<LevelPersistenceLevelSaveGameData>();

        [global::ProtoBuf.ProtoMember(48, Name = @"accumulated_level_persistence_reset_timer_seconds")]
        public uint AccumulatedLevelPersistenceResetTimerSeconds { get; set; }

        [global::ProtoBuf.ProtoMember(49, Name = @"mayhem_level")]
        public uint MayhemLevel { get; set; }

        [global::ProtoBuf.ProtoMember(50, Name = @"gbx_zone_map_fod_save_game_data")]
        public GbxZoneMapFODSaveGameData GbxZoneMapFodSaveGameData { get; set; }

        [global::ProtoBuf.ProtoMember(51, Name = @"active_or_blacklisted_travel_stations")]
        public global::System.Collections.Generic.List<ActiveFastTravelSaveData> ActiveOrBlacklistedTravelStations { get; } = new global::System.Collections.Generic.List<ActiveFastTravelSaveData>();

        [global::ProtoBuf.ProtoMember(52, Name = @"last_active_travel_station_for_playthrough")]
        public global::System.Collections.Generic.List<string> LastActiveTravelStationForPlaythroughs { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(53, Name = @"game_state_save_data_for_playthrough")]
        public global::System.Collections.Generic.List<GameStateSaveData> GameStateSaveDataForPlaythroughs { get; } = new global::System.Collections.Generic.List<GameStateSaveData>();

        [global::ProtoBuf.ProtoMember(54, Name = @"registered_downloadable_entitlements")]
        public global::System.Collections.Generic.List<RegisteredDownloadableEntitlements> RegisteredDownloadableEntitlements { get; } = new global::System.Collections.Generic.List<RegisteredDownloadableEntitlements>();

        [global::ProtoBuf.ProtoMember(55, Name = @"active_travel_stations_for_playthrough")]
        public global::System.Collections.Generic.List<PlaythroughActiveFastTravelSaveData> ActiveTravelStationsForPlaythroughs { get; } = new global::System.Collections.Generic.List<PlaythroughActiveFastTravelSaveData>();

        [global::ProtoBuf.ProtoMember(56, Name = @"save_game_guid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SaveGameGuid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(57, Name = @"guardian_rank_character_data")]
        public GuardianRankCharacterSaveGameData GuardianRankCharacterData { get; set; }

        [global::ProtoBuf.ProtoMember(58, Name = @"optional_objective_reward_fixup_applied")]
        public bool OptionalObjectiveRewardFixupApplied { get; set; }

        [global::ProtoBuf.ProtoMember(59, Name = @"vehicle_part_rewards_fixup_applied")]
        public bool VehiclePartRewardsFixupApplied { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class NicknameMappingsEntry : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"key")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Key { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"value")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Value { get; set; } = "";

        }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
